# Generated by Django 5.0.3 on 2024-03-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
